---
# tasks file for cis-windows-level1
- hosts: windows_server
  tasks:
  - name: CIS-L1 Account policies rules
    include_tasks: 1.0_AccountPolicies.yml
  - name: CIS-L1 Local policies, user management rules
    include_tasks: 2.2_LocalPolicies_UserRightsAssignment.yml
  - name: CIS-L1 Local policies, user management rules
    include_tasks: 2.3_LocalPolicies_SecurityOptions.yml
  - name: CIS-L1 9.0 Windows Firewall
    include_tasks: 9.0_Windows_Firewall.yml
  - name: CIS-L1 Advanced Audit Policy
    include_tasks: 17.0_Advanced_Audit_Policy_Config.yml

# HKU won't allow new registry paths to be created in the root folder
# https://docs.ansible.com/ansible/devel/modules/win_regedit_module.html#notes
#- name: CIS-L1 HKEY_USER Registry rules
#  include_tasks: 19-HKUreg.yml
